#ifndef IMAGENES_H_INCLUDED
#define IMAGENES_H_INCLUDED

BITMAP *buffer;

BITMAP *JUGADOR_spr;
BITMAP *JUGADOR_mov_spr;
BITMAP *JUGADOR_attack_spr;

BITMAP *ENEMIGO_1_spr;
BITMAP *ENEMIGO_1_mov_spr;

BITMAP *ENEMIGO_2_spr;
BITMAP *ENEMIGO_2_mov_spr;

BITMAP *ENEMIGO_3_spr;
BITMAP *ENEMIGO_3_mov_spr;

BITMAP *ENEMIGO_4_spr;
BITMAP *ENEMIGO_4_mov_spr;
BITMAP *ENEMIGO_4_cristal_spr;

BITMAP *PROYECTILES_spr;
BITMAP *PROYECTIL_mov_spr;

BITMAP *PILARES_spr;
BITMAP *RAYO_spr;

///--------------
BITMAP *FONDOS_spr;
BITMAP *MURO_spr;
BITMAP *PARED_spr;
BITMAP *PISO_spr;

///--------------
BITMAP *ELEMENTOS_spr;
BITMAP *ALTAR_spr;
BITMAP *PUERTA_spr;
BITMAP *DECORADO_spr;

///--------------
BITMAP *ANIMACIONES_spr;
BITMAP *ANIMACION_spr;

///--------------
BITMAP *BARRAS_spr;
BITMAP *BARRAS_ACT_spr;
BITMAP *CORAZON_spr;



#endif // IMAGENES_H_INCLUDED
