#ifndef IMAGENES_H_INCLUDED
#define IMAGENES_H_INCLUDED

BITMAP *buffer;

BITMAP *MURO_IRROMPIBLE_spr;
BITMAP *MURO_ROMPIBLE_spr;
BITMAP *COFRE_spr;
BITMAP *ENEMIGO_spr;
BITMAP *AVATAR_spr;
BITMAP *PUERTA_spr;
BITMAP *PISO_spr;

BITMAP *JUGADOR_spr;
BITMAP *JUGADOR_mov_spr;

///Decorado

BITMAP *ANTORCHA_spr;
BITMAP *ANTORCHA_efect_spr;

BITMAP *SANGRE_spr;
BITMAP *SANGRE_efect_spr;



#endif // IMAGENES_H_INCLUDED
