#ifndef IMAGENES_H_INCLUDED
#define IMAGENES_H_INCLUDED

BITMAP *buffer;

BITMAP *MURO_IRROMPIBLE_spr;
BITMAP *MURO_ROMPIBLE_spr;
BITMAP *COFRE_spr;
BITMAP *ENEMIGO_spr;
BITMAP *AVATAR_spr;
BITMAP *PUERTA_spr;
BITMAP *PISO_spr;

#endif // IMAGENES_H_INCLUDED
